version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11431:11431"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - OLLAMA_ORIGINS="http://0.0.0.0,http://localhost,https://localhost"
      - OLLAMA_HOST=0.0.0.0:11431
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    command: >
      bash -c "apt-get update && apt-get install -y postgresql-15-pgvector && docker-entrypoint.sh postgres"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/config:/app/config
      - backend_storage:/app/storage
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - ollama
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/config:/app/config
      - ./frontend/cache:/app/cache
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - backend


volumes:
  postgres_data:
  ollama_data:
  backend_storage:
  redis_data:

networks:
  backend:
    driver: bridge
